/**
 * email-signup — lead-gen band (replica of redballtennis.com section.signup,
 * the shared leadgen module on index/play/host).
 *
 * Decode tier: template-slotted. The block owns the leadgen form DOM and
 * NODE-SLOTS the authored elements into it (EW1).
 *
 * Schema: stardust/eds-schema/index-proposed.json, section "signup"
 * (10 items: heading, cta-text, field labels + asterisks, submit label,
 * terms body, 2 terms links).
 *
 * Authoring rows (positional; decode is query/order-based):
 *   1. band title — author as <h2> (prototype h4 canonicalised to the outline)
 *   2. cta-text paragraph (semibold call-to-action line)
 *   3. field 1 label — plain <p> (e.g. "EMAIL")
 *   4. field 2 label — plain <p> (e.g. "ZIP/POSTAL CODE")
 *   5. terms paragraph with the terms/privacy links inline
 *
 * The RBT icon, the two text inputs, the red asterisks and the disabled
 * "*JOIN THE FUN" button are FORM FURNITURE, generated by the block.
 * The form is VISUAL ONLY (dynamics disposition: interim) — action="#",
 * no working submit, button rendered disabled exactly as the pre-consent
 * live capture.
 *
 * @ew-exempt form control furniture (labels' asterisk spans, the disabled
 *   submit button text, input placeholders) — forms category: visual-only
 *   interim form; the generated control texts mirror the live capture and are
 *   not authorable content.
 */

// Wrap an AUTHORED element in a generated wrapper that carries the layout class.
function wrapNode(node, className) {
  const w = document.createElement('div');
  w.className = className;
  w.append(node);
  return w;
}

// Cell-level cascade collector (#62/#68/#71 + #104 wrapTextNodes expansion).
function collectNodes(block) {
  const out = [];
  block.querySelectorAll(':scope > div > div').forEach((cell) => {
    let kids = [...cell.children];
    if (kids.length === 1 && kids[0].tagName === 'P' && kids[0].children.length
        && kids[0].querySelector('picture, img')) {
      kids = [...kids[0].childNodes].map((n) => {
        if (n.nodeType === 1) return n;
        // HARNESS-ONLY fallback (EW5): bare text node inside the wrapper <p>.
        if (n.textContent.trim()) { const p = document.createElement('p'); p.append(n); return p; }
        return null;
      }).filter(Boolean);
    }
    if (kids.length) out.push(...kids);
    // HARNESS-ONLY fallback (EW5): bare-text cell (off-pipeline content only).
    else if (cell.textContent.trim()) {
      const p = document.createElement('p');
      p.append(...cell.childNodes);
      out.push(p);
    }
  });
  return out.length ? out : [...block.children];
}

// Fixed field furniture (visual-only interim form), labels node-slotted in.
const FIELDS = [
  { id: 'email-value', name: 'email', autocomplete: 'email' },
  { id: 'zipcode-value', name: 'zipcode', autocomplete: 'postal-code' },
];

export default async function decorate(block) {
  const nodes = collectNodes(block);

  // ── classify ──
  const heading = nodes.find((n) => n.matches('h1, h2, h3, h4, h5, h6'));
  const paras = nodes.filter((n) => n.matches('p') && n.textContent.trim());
  const terms = paras.find((p) => p.querySelector('a'));
  const plain = paras.filter((p) => p !== terms);
  const ctaText = plain[0];
  const labels = plain.slice(1, 1 + FIELDS.length);
  const consumed = new Set([heading, terms, ctaText, ...labels]);

  // ── build the template DOM ──
  const inner = document.createElement('div');
  inner.className = 'signup-inner';
  const leadgen = document.createElement('div');
  leadgen.className = 'leadgen';
  const inpage = document.createElement('div');
  inpage.className = 'leadgen-inpage';
  const form = document.createElement('form');
  form.className = 'leadgen-form';
  form.setAttribute('novalidate', '');
  // VISUAL ONLY (dynamics disposition: interim) — no working submit.
  form.setAttribute('action', '#');

  // brand icon — fixed template furniture (not authored content)
  const icon = document.createElement('img');
  icon.className = 'leadgen-icon';
  icon.src = '/assets/rbt-favicon-180x180.png';
  icon.alt = '';
  form.append(icon);

  if (heading) form.append(wrapNode(heading, 'leadgen-title'));
  if (ctaText) form.append(wrapNode(ctaText, 'leadgen-cta-text'));

  const inputs = document.createElement('div');
  inputs.className = 'leadgen-inputs';
  FIELDS.forEach((f, i) => {
    const field = document.createElement('div');
    field.className = 'field';
    const label = document.createElement('label');
    label.className = 'field-label';
    label.setAttribute('for', f.id);
    const asterisk = document.createElement('span');
    asterisk.className = 'field-asterisk';
    asterisk.textContent = '*';
    label.append(asterisk);
    if (labels[i]) label.append(labels[i]); // authored label <p> moved in (EW1)
    const input = document.createElement('input');
    input.className = 'field-input';
    input.id = f.id;
    input.type = 'text';
    input.name = f.name;
    input.setAttribute('autocomplete', f.autocomplete);
    input.setAttribute('required', '');
    field.append(label, input);
    inputs.append(field);
  });

  const submit = document.createElement('div');
  submit.className = 'leadgen-submit';
  const button = document.createElement('button');
  button.type = 'button';
  button.className = 'button';
  button.setAttribute('disabled', '');
  button.textContent = '*JOIN THE FUN '; // live capture: disabled-look interim
  submit.append(button);
  inputs.append(submit);
  form.append(inputs);

  if (terms) form.append(wrapNode(terms, 'leadgen-terms'));

  // leftovers pass: any authored element no named slot consumed stays visible
  nodes.forEach((n) => { if (!consumed.has(n) && !n.closest('form')) form.append(n); });

  inpage.append(form);
  leadgen.append(inpage);
  inner.append(leadgen);
  block.replaceChildren(inner);
}
